// Code generated by mockery v2.42.1. DO NOT EDIT.

package gluermocks

import mock "github.com/stretchr/testify/mock"

// Gluer is an autogenerated mock type for the Gluer type
type Gluer struct {
	mock.Mock
}

type Gluer_Expecter struct {
	mock *mock.Mock
}

func (_m *Gluer) EXPECT() *Gluer_Expecter {
	return &Gluer_Expecter{mock: &_m.Mock}
}

// Glue provides a mock function with given fields:
func (_m *Gluer) Glue() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Glue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Gluer_Glue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Glue'
type Gluer_Glue_Call struct {
	*mock.Call
}

// Glue is a helper method to define mock.On call
func (_e *Gluer_Expecter) Glue() *Gluer_Glue_Call {
	return &Gluer_Glue_Call{Call: _e.mock.On("Glue")}
}

func (_c *Gluer_Glue_Call) Run(run func()) *Gluer_Glue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Gluer_Glue_Call) Return(_a0 error) *Gluer_Glue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Gluer_Glue_Call) RunAndReturn(run func() error) *Gluer_Glue_Call {
	_c.Call.Return(run)
	return _c
}

// NewGluer creates a new instance of Gluer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGluer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Gluer {
	mock := &Gluer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
