// Code generated by MockGen. DO NOT EDIT.
// Source: routes.go

// Package gluermocks is a generated GoMock package.
package gluermocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockRoutesParser is a mock of RoutesParser interface.
type MockRoutesParser struct {
	ctrl     *gomock.Controller
	recorder *MockRoutesParserMockRecorder
}

// MockRoutesParserMockRecorder is the mock recorder for MockRoutesParser.
type MockRoutesParserMockRecorder struct {
	mock *MockRoutesParser
}

// NewMockRoutesParser creates a new mock instance.
func NewMockRoutesParser(ctrl *gomock.Controller) *MockRoutesParser {
	mock := &MockRoutesParser{ctrl: ctrl}
	mock.recorder = &MockRoutesParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoutesParser) EXPECT() *MockRoutesParserMockRecorder {
	return m.recorder
}

// MockRoutesAppender is a mock of RoutesAppender interface.
type MockRoutesAppender struct {
	ctrl     *gomock.Controller
	recorder *MockRoutesAppenderMockRecorder
}

// MockRoutesAppenderMockRecorder is the mock recorder for MockRoutesAppender.
type MockRoutesAppenderMockRecorder struct {
	mock *MockRoutesAppender
}

// NewMockRoutesAppender creates a new mock instance.
func NewMockRoutesAppender(ctrl *gomock.Controller) *MockRoutesAppender {
	mock := &MockRoutesAppender{ctrl: ctrl}
	mock.recorder = &MockRoutesAppenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoutesAppender) EXPECT() *MockRoutesAppenderMockRecorder {
	return m.recorder
}
